spring:
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
    h2:
      console:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/${FIREBASE_PROJECT_ID:test-project}
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com